export const homeEntries = [
  {
    id: 0,
    image: './assets/images/home-pictures/join.jpg',
    title: 'Join us',
    body: 'Join us on a journey down memory lane as we celebrate the past and embrace the future - your alumni community awaits!',
    url: '/stories',
  },
  {
    id: 1,
    image: './assets/images/home-pictures/fellow.jpg',
    title: 'Fellows',
    body: 'Reconnect, reminisce, and relive the good times with your fellow alumni. Let us make new memories together.',
    url: '/stories',
  },
  {
    id: 2,
    image: './assets/images/home-pictures/friends.jpg',
    title: 'Friends',
    body: 'Discover the alumni hub where old friends meet new opportunities. Unite, network, and thrive in our global community.',
    url: '/stories',
  },
  {
    id: 3,
    image: './assets/images/home-pictures/bonds.jpg',
    title: 'Bonds',
    body: 'The bonds that started here will never break. Get ready to reconnect with your alma mater and fellow graduates.',
    url: '/stories',
  },
  {
    id: 4,
    image: './assets/images/home-pictures/experience.webp',
    title: 'Experience',
    body: 'Your alumni experience begins here - connect with your roots, create lasting memories, and unlock a world of opportunities.',
    url: '/stories',
  },
  {
    id: 5,
    image: './assets/images/home-pictures/journey.jpg',
    title: 'Your Journey',
    body: 'From dorm rooms to boardrooms, your alumni journey continues. Rekindle old friendships and forge new connections.',
    url: '/stories',
  },
  {
    id: 6,
    image: './assets/images/home-pictures/inspriation.jpg',
    title: 'Inspiration',
    body: 'Stay connected, stay inspired. Join us as we celebrate the past, embrace the present, and shape the future.',
    url: '/stories',
  },
  {
    id: 7,
    image: './assets/images/home-pictures/memories.jpg',
    title: 'Your Memories',
    body: 'The alumni page that brings your memories to life. Join us for a nostalgia-filled journey and stay connected forever.',
    url: '/stories',
  },
  {
    id: 8,
    image: './assets/images/home-pictures/future.jpg',
    title: 'Your future',
    body: 'Reconnect with old friends, rediscover your passion, and reimagine your future with the support of our vibrant alumni community.',
    url: '/stories',
  },
];
